Assignment
Rantitope/shell pull request #1
Opened 2024-08-31 15:34 UTC by Rantitope

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
adding codes
## What did you learn from the changes you have made?
creating directories, deleting directories
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I was thinking of the 1st approach Simeon taught which is simpler
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I had challenges with the app, commiting, pushing etc. Pedram, learning support staff, was of great help in completing the assignment
## How were these changes tested?
I am not sure it was tested. I am open to learning
## A reference to a related issue in your repository (if applicable)

## Checklist
- [ ] I can confirm that my changes are working as intended
Yes

2024-09-02 18:14 UTC, dwz92 requested changes

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +file1.txt file2.txt file3.txt file4.txt file5.txt
This does not create anything

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +dir2 file3 'Hello world'
This also doesn't create anything. dir2 is not a command.

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +rem file4
`rm` not rem

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +rem file4
also missing .txt extension and specify dir2

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +dir2 file3 'Hello world'
use `>>`

2024-09-02 18:14 UTC, dwz92 commented on 02_activities/assignments/assignment.sh
> +file1.txt file2.txt file3.txt file4.txt file5.txt
look into `touch`

2024-09-03 09:46 UTC, merged

2024-09-03 10:14 UTC, Rantitope commented
Hello.
Am I expected to re-do the assignment, then submit or take note notes of the errors made?

    On Monday, September 2, 2024 at 02:15:15 PM EDT, Emma ***@***.***> wrote:  
 
 


@dwz92 requested changes on this pull request.

In 02_activities/assignments/assignment.sh:
>  # 3. Create 5 text files in dir2 named file1, file2, file3, file4, and file5
+file1.txt file2.txt file3.txt file4.txt file5.txt

This does not create anything

In 02_activities/assignments/assignment.sh:
>  
 # 4. Append the words "Hello world" to dir2/file3
-
+dir2 file3 'Hello world' 

This also doesn't create anything. dir2 is not a command.

In 02_activities/assignments/assignment.sh:
>  # 6. Delete file4
-
+rem file4

rm not rem

In 02_activities/assignments/assignment.sh:
>  # 3. Create 5 text files in dir2 named file1, file2, file3, file4, and file5
+file1.txt file2.txt file3.txt file4.txt file5.txt

look into touch

In 02_activities/assignments/assignment.sh:
>  
 # 4. Append the words "Hello world" to dir2/file3
-
+dir2 file3 'Hello world' 

use >>

In 02_activities/assignments/assignment.sh:
>  # 6. Delete file4
-
+rem file4

also missing .txt extension and specify dir2

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-09-04 21:26 UTC, dwz92 commented
no need to redo, just fix your mistakes and commits again.

But since you closed the PR, remember to create another PR after you fix your mistakes. And send me a text on slack when you are done